### ISSUE TITLE
[自荐] coderplanets 求收录

### ISSUE THREAD

**Issue by mydearxym** [wubaiqing/zaobao#10]
@wubaiqing  你好

不知道能不能将 [coderplanets](https://github.com/coderplanets) 项目添加到你的 zaobao 中 ?

我在 ruby-china 上发过详细的介绍帖： https://ruby-china.org/topics/38052

**Comment by wsdjeg** [comment]
支持一波，这样的收录更加有实际意义

**Comment by wubaiqing** [comment]
感谢你的自荐：

源码中有些库是值得推荐的，但单纯从项目中，我有这几个疑问：
* 这次自荐的项目在实际业务当中的“痛点”的什么？
* 它能解决什么问题？
* 因为是多个项目，包含：前台、管理后台、server，那么怎么能快速的启动你的服务？
* 帮助的人群是谁？我没有留意到。

**Comment by mydearxym** [comment]
@wsdjeg 非常感谢 :) 希望有时间能去坐坐提点意见 :)

**Comment by mydearxym** [comment]
@wubaiqing 你好 

你提到的问题在上面的介绍帖子里有部分回答。 但是我并不知道你收录的分享是技术细节层面的，我更多是从产品角度来出发的。

多有打扰。
