### ISSUE TITLE
2019.02.06 链接放错了，麻烦修改一下，辛苦了

### ISSUE THREAD

**Issue by donlinglok1** [wubaiqing/zaobao#12]
[类库] Lozad.js 是基于 IntersectionObserver API 的轻量级、高性能、可配置的纯 JavaScript 并且无依赖的懒加载器，其能够被用于进行图片、iframe 等多种形式的元素：https://github.com/alexmacarthur/typeit

**Comment by wubaiqing** [comment]
谢谢指正，链接已修复。
