### ISSUE TITLE
每日时报网站样式建议

### ISSUE THREAD

**Issue by Mongkii** [wubaiqing/zaobao#125]
https://wubaiqing.github.io/zaobao/2020/08/21.html 这一篇，链接中连续字母太多，以致溢出盒子
可以考虑用 `word-break: break-all;` 处理一下链接的样式

**Comment by wubaiqing** [comment]
感谢，我们尽快修复。

**Comment by wubaiqing** [comment]
> https://wubaiqing.github.io/zaobao/2020/08/21.html 这一篇，链接中连续字母太多，以致溢出盒子
> 可以考虑用 `word-break: break-all;` 处理一下链接的样式

已修复 https://github.com/wubaiqing/zaobao/commit/d716b199719ec80625dfbc2b2dc1cac509da4a93 感谢。
