### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by xxholly32** [wubaiqing/zaobao#140]
# 2个问题

## 段落标示问题

一般文章都是以 # ## ### #### ... 代表 h1 h2 h3 h4...

而每日文章以 ### 开头，而配图却是 # ，写起来非常别扭。

## 文章分类问题

内容会以：文章、工具、新闻、视频等几大板块作为主要分类。

+ 新闻其实包含所有，基本上都是拿新的东西来上zaobao，选起来比较纠结，一般我是没什么选了，才写新闻的
+ 一些其他分类
 - 模版项目或者一些优秀网站属于的类型
 - 类库 or 工具? 比如脚手架是工具还是类库呢？

**Comment by wubaiqing** [comment]
其实配图也是 `###`。我写错了，今天会批量改下。

分类的名词定义：

【新闻】如：Google V8 引擎新增了哪些特性或标准，TypeScript 新版本出了哪些特性，新鲜的事物「新跨域策略 COOP、COEP、早期的模块联邦、微前端等等」处于早期刚刚了解到还没有正式商用的，我一般会放在新闻的分类下。等大家都了解了，遇到文章写的特别好的，质量高的，会放在文章分类下。所以新闻这个分类，只对新事物保留，而且会放在顶部。

【文章】非新鲜事物，有技术成长性、对我自身起到一定帮助的、写作质量较高还不是大众化的，我一般会作为文章的分类。
 
【工具】这个工具是 CLI 工具或者是 Electron 开发的软件，比如 Umi、PicGo、Vue CLI（vue create、vue ui）、npm publish、cnpm 一般不作为项目中使用的，可以帮助我们提升效率的，我理解为工具。

【类库】类库相对来说就比较好理解，比如说 Swiper 以及项目当中会用 requrie 或 import 引入的库，服务于业务中，归属于类库。

【视频】视频讲解的内容，新鲜的放在新闻中，如早期的协成。非新鲜的，常见是各类技巧，开源教程，会放在视频分类当中。

**Comment by xxholly32** [comment]
分类定义应该清楚了，文章章节还有点异议

遵循文章编写原则的话 最上层应该是 # 接着是 ##，如果觉得样式不对的话可以统一在样式文件中修改。

很多情况下我想找以前的文章必须每个日期回头去点，但`vuepress`的搜索其实已经实现了绑定章节的功能了，所以建议文章分类也用标题展示，否则搜出来基本都是配图

![image](https://user-images.githubusercontent.com/6063358/95825520-8f2dd100-0d63-11eb-8b8c-91f094030ce2.png)

**Comment by wubaiqing** [comment]
> 分类定义应该清楚了，文章章节还有点异议
> 
> 遵循文章编写原则的话 最上层应该是 # 接着是 ##，如果觉得样式不对的话可以统一在样式文件中修改。
> 
> 很多情况下我想找以前的文章必须每个日期回头去点，但`vuepress`的搜索其实已经实现了绑定章节的功能了，所以建议文章分类也用标题展示，否则搜出来基本都是配图
> 
> ![image](https://user-images.githubusercontent.com/6063358/95825520-8f2dd100-0d63-11eb-8b8c-91f094030ce2.png)

确实，我也发现搜索很难用，可以试一下看看效果如何。
