### ISSUE TITLE
RSS 没有及时更新

### ISSUE THREAD

**Issue by bifan** [wubaiqing/zaobao#208]
## 现象：
<img width="1378" alt="2021-07-23_17-29-41" src="https://user-images.githubusercontent.com/2929293/126763419-045d4e32-d0ed-4af7-922c-ae57d3ef7624.png">
从图中可以看出23小时前一次性更新了6篇

## 环境：
我用的是Inoreader 订阅的RSS
<img width="519" alt="2021-07-23_17-33-13" src="https://user-images.githubusercontent.com/2929293/126763901-43de8136-4329-47d0-b918-297e38ace1f9.png">

**Comment by wubaiqing** [comment]
没有及时更新 gh-pages 分支导致的。
