### ISSUE TITLE
新闻源是从哪里爬取的呢?

### ISSUE THREAD

**Issue by usherwong** [wubaiqing/zaobao#22]
如题，想问下新闻的来源。还有就是自动爬去的话，楼主是否要做一层筛选呢，筛选是人工的还是自动化的呢。又没有比较方便的方式？感谢

**Comment by wubaiqing** [comment]
你好：

便捷的方式，无非是从[聚合](https://devurls.com/)里阅读你感兴趣的文章；其次是 Twitter、Youtube 的关注列表。

早报项目最有价值的“点”是信息源，如果我都觉得不好也不会分享给大家了，所以新闻和文章都是我看过，才分享出来的。

我的方式是人工筛选，信息量太多对于我来说并不是件好事，会看不过来也看的不细。
