### ISSUE TITLE
【工具自荐】点击页面元素自动打开编辑器并跳转到Vue组件

### ISSUE THREAD

**Issue by webfansplz** [wubaiqing/zaobao#222]
一个点击页面元素自动打开编辑器并跳转到Vue组件的Vite插件

- [项目地址](https://github.com/webfansplz/vite-plugin-vue-inspector)
- [原理解析文章](https://juejin.cn/post/7077347158545924127)

**Comment by wubaiqing** [comment]
棒，我们之前在 Vue CLI 时代还实现过这个。

**Comment by wubaiqing** [comment]
https://github.com/wubaiqing/zaobao/commit/9bb64c3888f46501b5cabfa228d14eee8c04ff1b
