### ISSUE TITLE
更新频率低了好多呢？

### ISSUE THREAD

**Issue by fengyinchao** [wubaiqing/zaobao#226]
干不动了嘛，快一个月没更新啦

**Comment by wubaiqing** [comment]
早报更新了有将近四年的时间，对自己带来最大的好处是知识的广度。

现阶段的问题并不是广度了解的不够多，而是欠缺深度。

目前还在调整自己的状态，没有断更的计划。感谢你的监督。

**Comment by ZombieBrand** [comment]
周更也可以呀. 加油💪
