### ISSUE TITLE
老哥老哥，加个评论模块可好

### ISSUE THREAD

**Issue by refanbanzhang** [wubaiqing/zaobao#23]
类似下面这样的
![Snipaste_2019-03-19_09-17-56](https://user-images.githubusercontent.com/13738577/54573644-1d2ac400-4a28-11e9-872c-e078389272cb.png)

**Comment by wubaiqing** [comment]
评论模块有可以推荐的吗？最好是有带审核的功能。

**Comment by refanbanzhang** [comment]
看下这个
[https://vssue.js.org/zh/](https://vssue.js.org/zh/)

**Comment by wubaiqing** [comment]
已加评论模块，先试一段时间看看。 #41

**Comment by huiyifyj** [comment]
为什么不用 [gitalk/gitalk](https://github.com/gitalk/gitalk) ?
