### ISSUE TITLE
2019.03.28-超链接错了

### ISSUE THREAD

**Issue by bifan** [wubaiqing/zaobao#26]
This one：
    [资源] 小火柴的前端小册子，总结了前端知识点，并且有实际演示效果

辛苦！

**Comment by IceApriler** [comment]
不确定是不是 https://www.xiaohuochai.cc/， 等 @wubaiqing 来改吧。🤣

**Comment by wubaiqing** [comment]
谢谢指正，链接已修复：https://www.xiaohuochai.site/
