### ISSUE TITLE
快速将Photoshop设计稿中的阴影效果转换为CSS3代码

### ISSUE THREAD

**Issue by kensxiao** [wubaiqing/zaobao#30]
正好现在挺流行半扁平化设计，会用到各种投影效果，而很多设计师和前端人员并没有使用其他类似的快速工具。
地址是：https://psd2css.mezw.com/

**Comment by wubaiqing** [comment]
如果能实时的看到 “更新代码” 后的效果就更好了，比如：

当我改动了一些参数，能在下方直观的看到，施加在 「按钮、div」 上的效果。
