### ISSUE TITLE
等了好几天了，大佬什么时候更新哇

### ISSUE THREAD

**Issue by onelady** [wubaiqing/zaobao#33]
从4号开始等到9号了，没有早报的日子不开心了

**Comment by refanbanzhang** [comment]
me too

**Comment by refanbanzhang** [comment]
[用这个解解渴](https://daily.fairyever.com/article/chrome-extension.html)

**Comment by refanbanzhang** [comment]
![Snipaste_2019-04-09_17-09-33](https://user-images.githubusercontent.com/13738577/55788130-52d44180-5aea-11e9-8378-10f0505b75b2.png)
太简陋了，差评

**Comment by onelady** [comment]
> ![Snipaste_2019-04-09_17-09-33](https://user-images.githubusercontent.com/13738577/55788130-52d44180-5aea-11e9-8378-10f0505b75b2.png)
> 太简陋了，差评

尴尬了

**Comment by refanbanzhang** [comment]
> > ![Snipaste_2019-04-09_17-09-33](https://user-images.githubusercontent.com/13738577/55788130-52d44180-5aea-11e9-8378-10f0505b75b2.png)
> > 太简陋了，差评
> 
> 尴尬了

更新下啊，以后换工作很有用

**Comment by wubaiqing** [comment]
老家有事，从今日起恢复更新。谢谢大家一直在关注。
