### ISSUE TITLE
我是不是你最疼爱的人？你为什么不更新？

### ISSUE THREAD

**Issue by refanbanzhang** [wubaiqing/zaobao#35]
如题

**Comment by leeggco** [comment]
我每天都刷，最近都没有了。。

**Comment by refanbanzhang** [comment]
> 我每天都刷，最近都没有了。。

暂时用下面这个解解渴吧
[D2日报](https://daily.fairyever.com/article/chrome-extension.html)

**Comment by ycjcl868** [comment]
...

**Comment by refanbanzhang** [comment]
> ...

有话直说，...是什么意思？

**Comment by wubaiqing** [comment]
老家有事，从今日起恢复更新。

**Comment by ycjcl868** [comment]
@gaoqiang19514 有发 issue 吐槽的时间都帮 @wubaiqing 更了，还最疼爱的人。。。

**Comment by wubaiqing** [comment]
@gaoqiang19514 

这位老哥一直是监督我的人，也非常感谢他的催更。

谢谢大家伙的持续关注，下次有事会跟大家请假。
