### ISSUE TITLE
[Vssue]Vssue Talk

### ISSUE THREAD

**Issue by wubaiqing** [wubaiqing/zaobao#41]
https://wubaiqing.github.io/zaobao/talk/

**Comment by refanbanzhang** [comment]
我来组成头部
![收声](http://img.youai123.com/5b24c8602d1ff-min.jpg)

**Comment by leeggco** [comment]
我来组成脖子

**Comment by bifan** [comment]
2019.04.19 - 配图 - Java 为啥是只鸡呢
老母鸡生蛋(data), 蛋催化为雏(html), 雏披绚羽(css), 蹦跶(js)
( •̀ ω •́ )y

**Comment by qinjker** [comment]
博主，弱弱的问一句，每篇文章里面最后的配的gif图片你是自己做的吗？

**Comment by wubaiqing** [comment]
> 博主，弱弱的问一句，每篇文章里面最后的配的gif图片你是自己做的吗？

@qinjker 不是我做的，都是来源于网络。逗大家伙开心的。

**Comment by qinjker** [comment]
@wubaiqing

> > 博主，弱弱的问一句，每篇文章里面最后的配的gif图片你是自己做的吗？
> 
> @qinjker 不是我做的，都是来源于网络。逗大家伙开心的。

哦 好的，谢谢！这种是一般都是通过gif工具制作的是吧？

**Comment by wubaiqing** [comment]
> @wubaiqing
> 
> > > 博主，弱弱的问一句，每篇文章里面最后的配的gif图片你是自己做的吗？
> > 
> > 
> > @qinjker 不是我做的，都是来源于网络。逗大家伙开心的。
> 
> 哦 好的，谢谢！这种是一般都是通过gif工具制作的是吧？

一般都是视频转 Gif。

**Comment by javaLuo** [comment]
表示支持，
我每天都来看报，博主你哪些天偷懒没更我都一清二楚

**Comment by wubaiqing** [comment]
> 表示支持，
> 我每天都来看报，博主你哪些天偷懒没更我都一清二楚

感谢支持和监督。

**Comment by chenchujuan** [comment]
弱弱问一句博主这个博客您是怎么拿数据的，没看到有ajax请求

**Comment by refanbanzhang** [comment]
@javaLuo

> 表示支持，
> 我每天都来看报，博主你哪些天偷懒没更我都一清二楚
> 

颇有些恐吓意味
![表情包](http://wx3.sinaimg.cn/large/006R4mNygy1fvf07wm3rdj30jg0iit9a.jpg)

**Comment by bougieL** [comment]
人民币上的竹篮脱单了

**Comment by sunbufu** [comment]
人民币那个，是多了个篮子🧺。

**Comment by refanbanzhang** [comment]
@sunbufu

> 人民币那个，是多了个篮子🧺。

人篮恋不允许？

**Comment by victor-fa** [comment]
RenZhengfei 的库被他的作者删除了…… 还好我下载了……

**Comment by wubaiqing** [comment]
> RenZhengfei 的库被他的作者删除了…… 还好我下载了……

我看了下链接，还在呀：https://github.com/benmahr/RenZhengfei

**Comment by refanbanzhang** [comment]
@wubaiqing

> > RenZhengfei 的库被他的作者删除了…… 还好我下载了……
> 
> 我看了下链接，还在呀：https://github.com/benmahr/RenZhengfei

404

**Comment by GreatAuk** [comment]
每天上来看看，已经成习惯了。

**Comment by wubaiqing** [comment]
> 每天上来看看，已经成习惯了。

就像是 JavaLuo 说的「每天都来看报，博主你哪些天偷懒没更我都一清二楚」

**Comment by xiaoxielnino** [comment]
hello, 顶部的搜索功能好像没有生效，比如说 我搜hooks，我看了发了请求，结果也有了，但是没有显示出来呢

**Comment by Kerinlin** [comment]
年字前面多了个 口 字?

**Comment by JiangXue93** [comment]
咦~现在“每日时报”不每日了么_(:з」∠)_

**Comment by victor-fa** [comment]
2019.07.11中：
 一款真正的跨平台摸鱼神器，可以更加隐秘性大胆的看小说：https://github.com/cteams/Thief-Book

地址改了，改成：https://github.com/cteamx/Thief-Book

**Comment by victor-fa** [comment]
显示 GitHub 里项目 Star 进展的工具
无法统计vue，估计后台直接崩溃了[手动狗头]
https://starchart.cc/vuejs/vue

**Comment by qinjker** [comment]
最近发现一个远程面试的好工具 https://www.showmebug.com

**Comment by chf007** [comment]
![http://qn.40zhe.com/16d3e211a936b9c7](http://qn.40zhe.com/16d3e211a936b9c7)

这个蓝湖的bug，去年就和他们提了，他们不认为是 bug

![https://sm.ms/image/MrAxBRm2ej9aSct](https://sm.ms/image/MrAxBRm2ej9aSct)
![https://sm.ms/image/zBpUTo9Kqkc2adP](https://sm.ms/image/zBpUTo9Kqkc2adP)
![https://sm.ms/image/TEb2PX8WOzYmc4A](https://sm.ms/image/TEb2PX8WOzYmc4A)
![https://sm.ms/image/jTlNwbOeV7QuXSY](https://sm.ms/image/jTlNwbOeV7QuXSY)

**Comment by FEJackFly** [comment]
2019年10月24日 博主偷偷摸鱼 没有跟新 不知道是不是公司有鼓励师 乱了阵脚

**Comment by Kerinlin** [comment]
催更,催更

**Comment by reygreen1** [comment]
好像没有看到最近几天的更新了？

**Comment by YUUtan1994** [comment]
rss不能用了亲，目前还停留在12。27号

**Comment by linshuizhaoying** [comment]
happy new year!

**Comment by LDingLDing** [comment]
我来催更了～

**Comment by sanbeichahegongheguo** [comment]
是啊，已经不能算是每日报了。

**Comment by KingAmo** [comment]
好久没更新了...工作很忙吧？

**Comment by linshuizhaoying** [comment]
终于恢复更新了

**Comment by refanbanzhang** [comment]
失踪人口回归

**Comment by BenjaminX** [comment]
总算又恢复更新了。

**Comment by cMing1997** [comment]
现在搜索处于无响应状态，浏览器环境：appVersion: "5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

**Comment by xkloveme** [comment]
我来催更

**Comment by bodyno** [comment]
最近更新频率下降了好多

**Comment by sunthx** [comment]
# 整天拖更啊。
# 又拖更啊。
# 今天的主题是：怎么又拖更。

**Comment by Grewer** [comment]
想问问数据来源是啥, 靠人工录入, 还是爬虫获取

**Comment by Allen-0827** [comment]
1个月没更了啊 ░▏▎▍▌▋▊▉█
