### ISSUE TITLE
留言页无法滚动

### ISSUE THREAD

**Issue by refanbanzhang** [wubaiqing/zaobao#43]
在留言页面按`F5`刷新，会出现顶部被盖住且没有滚动条，无法滚动的情况（`chrome`和`firefox`）

系统：win10

浏览器厂商：chrome
浏览器版本： 73.0.3683.103（正式版本） （64 位）

浏览器厂商：firefox
浏览器版本： 66.0.3 (64 位)

![Snipaste_2019-04-17_09-14-57](https://user-images.githubusercontent.com/13738577/56254192-65560880-60f2-11e9-82d8-cf532f6dc27d.png)

**Comment by wubaiqing** [comment]
像是浏览器缩放了，试试：
Windows 平台：ctrl + 0；
Mac 平台：command + 0；

**Comment by refanbanzhang** [comment]
> 像是浏览器缩放了，试试：
> Windows 平台：ctrl + 0；
> Mac 平台：command + 0；

没有缩放
![image](https://user-images.githubusercontent.com/13738577/56255657-4a869280-60f8-11e9-9db7-3349fa4aab88.png)

**Comment by gaoqiang19514** [comment]
火狐也能复现
![Snipaste_2019-04-17_10-07-23](https://user-images.githubusercontent.com/13738577/56255768-a18c6780-60f8-11e9-903f-6d2f8819d508.png)

**Comment by wubaiqing** [comment]
已修复。https://github.com/wubaiqing/zaobao/commit/396a1218513b2bcd0da8a6633aa8ab6e8a1a52fe

**Comment by refanbanzhang** [comment]
nice老哥
