### ISSUE TITLE
新浪图床403

### ISSUE THREAD

**Issue by xiaotianxia** [wubaiqing/zaobao#45]
https://ws1.sinaimg.cn/* 返回403

**Comment by wubaiqing** [comment]
> https://ws1.sinaimg.cn/* 返回403

哪篇的日报地址呢？

**Comment by xiaotianxia** [comment]
https://wubaiqing.github.io/zaobao/2019/04/26.html
![image](https://user-images.githubusercontent.com/8045122/56858630-0fb21380-69b0-11e9-8d0e-d30c762a9617.png)
看了一下这篇有两个
貌似前面的也有

**Comment by huiyifyj** [comment]
新浪图床不支持外链使用了，除非新建标签页打开。

**Comment by wubaiqing** [comment]
> 新浪图床不支持外链使用了，除非新建标签页打开。

好，我查一下，如果是这种情况的话会考虑换图床。
