### ISSUE TITLE
8月22号公司团建，跟大家伙请下假。

### ISSUE THREAD

**Issue by wubaiqing** [wubaiqing/zaobao#46]
# 我去浪了啊...
![](http://qn.40zhe.com/16cb217ed4d1971f)

**Comment by refanbanzhang** [comment]
![微信图片_20190508140612](https://user-images.githubusercontent.com/13738577/57353246-739bbf80-719a-11e9-89e7-b5089d34cdc9.jpg)

**Comment by kangchihlun** [comment]
作為一個每日收看的吃瓜群眾來說，偷偷地來跟大老說聲：感謝有您。

**Comment by rquanx** [comment]
ojbk

**Comment by wubaiqing** [comment]
> 作為一個每日收看的吃瓜群眾來說，偷偷地來跟大老說聲：感謝有您。

哦了！

**Comment by wubaiqing** [comment]
我回来了！
