### ISSUE TITLE
链接有误

### ISSUE THREAD

**Issue by zxhycxq** [wubaiqing/zaobao#47]
2019.04.15

> [工具] Octotree 是一个 Chrome 扩展插件，其目的是在 GitHub 左侧，追加代码的树形结构的导航栏，方便查阅代码：https://github.com/jaywcjlove/linux-command

最后的链接不对吧？

**Comment by wubaiqing** [comment]
@zxhycxq 

非常感谢，能提 Issue 指正我的错误；链接确实放错了，文档已改。
正确的链接是：https://github.com/ovity/octotree
