### ISSUE TITLE
推荐:imgcook 通过设计稿智能生成代码

### ISSUE THREAD

**Issue by ff131517** [wubaiqing/zaobao#5]
通过设计稿一键智能生成视图代码，目前支持生成 Vue、React、Html5、Weex Rax 等常见 DSL。
淘宝出品 现在只是体验版

**Comment by ff131517** [comment]
https://github.com/taobaofed/imgcook

**Comment by wubaiqing** [comment]
👍哇，之前都没见过；我会测试一下，如果主流程走通，会收录到 2019.01.26 日报中。谢谢

**Comment by wubaiqing** [comment]
已收录至：<https://wubaiqing.github.io/zaobao/2019/01/26.html>，谢谢分享。
