### ISSUE TITLE
《大前端面试宝典 - 图解前端》

### ISSUE THREAD

**Issue by azl397985856** [wubaiqing/zaobao#50]
这是一份自己总结的关于准备前端面试的一个复习汇总项目，项目不定时更新。

这不仅仅是一份用于求职面试的攻略，也是一份前端er用来检视自己，实现突破的宝典。 希望通过这个指南，大家可以打通自己的任督二脉，在前端的路上更进一步。

本仓库大量采用图的形式来传达知识，所谓一图胜千言，希望通过这种图文并茂的表达方式 让你更容易记住一些抽象，难以理解的概念，《图解前端》是我给它的副标题。

所有的内容按照主题进行分类，大家可以根据自己需要随意传送, 我的目标是做`宇宙最强的前端面试指南。`

项目地址：https://github.com/azl397985856/fe-interview
在线阅读： https://lucifer.ren/fe-interview/#/

**Comment by wubaiqing** [comment]
提供一个建议：
可以按照层级，来区分目录结构；比如对标蚂蚁金服职级，优先要先看哪些？
那么我的目录结构就可以这么划分：P4（初级）、P5（中级）、P6（高级）、P7（专家）、P8（高级专家）。

以 P7 举例，他应该具备的技术栈至少有：
1. Docker
2. K8S
3. 负载均衡
4. 分布式
5. CDN 网络知识
6. HTTP 缓存
7. 单元测试
8. 持续集成
9. 性能分析+调优
10. 链路追踪
11. 依靠工具，而不是经验
12. 能制造工具，解决当前团队的问题
13. 具备良好的沟通以及表达能力，在公司/业界是公认领域的专家

所以推荐你的项目，最好针对人群、针对职级。

比如，当我看 P5（中级）工程师级别的题，发现，有可能不达标，那么缺少的是哪部分，就可以通过看你的宝典，来指正我一个方向补充。或者就降低一下标准，看看 P4（初级）工程师，我是否完全符合要求。先补充 P4 的遗漏，然后在补充 P5 的问题。

**Comment by wubaiqing** [comment]
已收录 2019.07.17 https://github.com/wubaiqing/zaobao/commit/c2d1bd38abb89ce8e91574d347d4618224b4333c

**Comment by azl397985856** [comment]
> 提供一个建议：
> 可以按照层级，来区分目录结构；比如对标蚂蚁金服职级，优先要先看哪些？
> 那么我的目录结构就可以这么划分：P4（初级）、P5（中级）、P6（高级）、P7（专家）、P8（高级专家）。
> 
> 以 P7 举例，他应该具备的技术栈至少有：
> 
> 1. Docker
> 2. K8S
> 3. 负载均衡
> 4. 分布式
> 5. CDN 网络知识
> 6. HTTP 缓存
> 7. 单元测试
> 8. 持续集成
> 9. 性能分析+调优
> 10. 链路追踪
> 11. 依靠工具，而不是经验
> 12. 能制造工具，解决当前团队的问题
> 13. 具备良好的沟通以及表达能力，在公司/业界是公认领域的专家
> 
> 所以推荐你的项目，最好针对人群、针对职级。
> 
> 比如，当我看 P5（中级）工程师级别的题，发现，有可能不达标，那么缺少的是哪部分，就可以通过看你的宝典，来指正我一个方向补充。或者就降低一下标准，看看 P4（初级）工程师，我是否完全符合要求。先补充 P4 的遗漏，然后在补充 P5 的问题。

这部分我也有考虑如何满足不同层级，包括后面的题也做了一定区分。
但是如你所说，并不完善。 还有前面我写的Job Model都是想去做一些区分的。

但是如果直接如你所说去区分，可能会有重复。  因此我现在在考虑折中的方案。

**Comment by wubaiqing** [comment]
> 这部分我也有考虑如何满足不同层级，包括后面的题也做了一定区分。
> 但是如你所说，并不完善。 还有前面我写的Job Model都是想去做一些区分的。
> 
> 但是如果直接如你所说去区分，可能会有重复。 因此我现在在考虑折中的方案。

是的，这么做会有重复，重复的例子如下：

**P4级 - HTTP 协议：**
会讲解常用 Methods，如：GET、POST、PUT、DELETE、OPTIONS

**P5级 - HTTP 协议：**
会讲解不太常用 Methods，如：链路追踪，消息环回

之前我收录过这些面试汇总，希望你的方案在几个项目之间，具有较高的辨识性：
1. https://github.com/Advanced-Frontend/Daily-Interview-Question
2. https://github.com/haizlin/fe-interview
3. https://github.com/semlinker/reactjs-interview-questions

期待 👍

**Comment by azl397985856** [comment]
okay， 另外非常感谢提供的意见和资料 🙏
