### ISSUE TITLE
bug: the title has 

### ISSUE THREAD

**Issue by xrkffgg** [wubaiqing/zaobao#52]
https://github.com/wubaiqing/zaobao/blob/e6ab94c7ba8c3abd79732c56c5912f1ac9adc38c/docs/.vuepress/config.js#L41

### Img
![](https://github.com/xrkffgg/Kimg/blob/master/others/001.png?raw=true)

### Environment
windows10
Chrome

😂😂😂

Are you deliberate?

**Comment by wubaiqing** [comment]
It's been repaired. Thank you for your advice.
