### ISSUE TITLE
9月3号链接错误

### ISSUE THREAD

**Issue by spike-bepop** [wubaiqing/zaobao#53]
> [类库] 京东风格的移动端 Vue 组件库 NutUI 2.0 来啦：https://www.zhangxinxu.com/wordpress/2019/08/js-dom-mutation-observer/

**Comment by wubaiqing** [comment]
谢谢指正，已修复：https://github.com/wubaiqing/zaobao/commit/87c28ad03e4018addadc2d038fd2861ca2be1105
