### ISSUE TITLE
[推荐] Quasar Framework

### ISSUE THREAD

**Issue by spike-bepop** [wubaiqing/zaobao#59]
[Quasar Framework](https://quasar.dev/introduction-to-quasar) 是一个设计极其优秀的ui组件库，组件丰富，所有组件使用flex布局，支持移动/PC端，支持第三方提供插件，支持打包成PWA、Cordova、Electron应用。

**Comment by wubaiqing** [comment]
感谢分享，已发布在 10月25号 的日报中：https://wubaiqing.github.io/zaobao/2019/10/25.html
