### ISSUE TITLE
信息来自哪里？

### ISSUE THREAD

**Issue by funlee** [wubaiqing/zaobao#6]
如题，每日日报的内容都是自己搜集的吗

**Comment by wubaiqing** [comment]
信息来源在 README.md 中有介绍

> 以我举例，我经常在（[Hacker News](https://news.ycombinator.com/)、[Medium](https://medium.com/)、[Dev.to](https://dev.to/)、[Twitter](https://twitter.com/)、[阮一峰](http://www.ruanyifeng.com/blog/)、[GitHub 关注](https://github.com/)、[微博](https://weibo.com/)、[V2EX](https://www.v2ex.com/)、[Ruby China](https://ruby-china.org/)、[GitHub Trending](https://github.com/trending)、[掘进](https://juejin.im/)、[OS China](https://www.oschina.net/)）等地去学习。通过整理后，把每天值得分享的内容，发布到公司的 QQ 群里，让大家和我同时受益。

目前日报 80% 的信息是自己搜集；一部分是来自于 GitHub 的开发者提供；还有一部分是来自公司的内部分享；
