### ISSUE TITLE
[推荐] Capacitor

### ISSUE THREAD

**Issue by spike-bepop** [wubaiqing/zaobao#60]
[Capacitor](https://capacitor.ionicframework.com/docs/getting-started/)是由ionic团队最新开发维护的一个跨平台的应用程序容器，可以轻松构建在iOS，Android，Electron 和 Web 上本机运行的Web应用程序。

**Comment by wubaiqing** [comment]
感谢分享，已发布在 10月25号 的日报中：https://wubaiqing.github.io/zaobao/2019/10/25.html
