### ISSUE TITLE
[推荐] 中国传统色在线手册

### ISSUE THREAD

**Issue by zerosoul** [wubaiqing/zaobao#61]
偶然间看到一个日本人在 2010 年的一个作品（ http://nipponcolors.com/），非常喜欢，用 react 重构了中国风界面， 重写 UI，并加入了一些细节改进和特有功能：

1. 颜色做了分类，更方便查找
2. 可收藏喜欢的颜色
3. 可生成壁纸，用来当手机壁纸，效果还可以
4. 加入诗词

访问地址： https://colors.ichuantong.cn/
代码开源： https://github.com/zerosoul/chinese-colors

界面UI：
![image](https://user-images.githubusercontent.com/2985895/67451162-38ab1c80-f652-11e9-8947-df2f251cd9f6.png)

手机壁纸：
![image](https://user-images.githubusercontent.com/2985895/67451020-cafef080-f651-11e9-849f-35d492c8e27d.png)

**Comment by wubaiqing** [comment]
哇塞，相当的赞！👍

**Comment by wubaiqing** [comment]
感谢分享，已发布在 10月25号 的日报中：https://wubaiqing.github.io/zaobao/2019/10/25.html
