### ISSUE TITLE
[工具] 基于React的弹幕npm包

### ISSUE THREAD

**Issue by zerosoul** [wubaiqing/zaobao#62]
临近年底，公司年会要做个弹幕上墙的功能，索性做成了npm包，分享出来供大家使用。

基于CSS3动画，使用React构建，性能还成。兼容性上还有待反馈。

目前具备的特性：

- 支持传入 React 组件，灵活控制弹幕内容和 UI，并提供一个默认样式组件：`<StyledBullet/>`
- 弹幕屏幕管理：清屏，暂停，隐藏（后续可能会加入针对单个弹幕的控制）
- 弹幕动画参数化：运动函数（匀速/ease/步进/cubic-bezier）、时长（秒）、循环次数等
- 鼠标悬浮弹幕暂停

体验地址：（上面提到的参数化配置默认随机展现）
https://zerosoul.github.io/rc-bullets/
源码地址：
https://github.com/zerosoul/rc-bullets

**Comment by wubaiqing** [comment]
👍 细节到位，效果不错。

**Comment by zerosoul** [comment]
> 👍 细节到位，效果不错。

谢谢 细节上确实下了点功夫 后续想在玩法上做些扩展~~~😄
