### ISSUE TITLE
2019.12.12 标题与配图不符

### ISSUE THREAD

**Issue by zhang1pr** [wubaiqing/zaobao#67]
[标题](https://wubaiqing.github.io/zaobao/2019/12/12.html#%E9%85%8D%E5%9B%BE-cli-color)与下面的配图不符。配图属于[[文章] 深入理解 JavaScript 原型和闭包系列，我目前看到第九章，通俗易懂值得推荐：](https://www.cnblogs.com/wangfupeng1988/p/4001284.html)。

**Comment by wubaiqing** [comment]
已修复，谢谢。
