### ISSUE TITLE
2020/02/12 链接错误

### ISSUE THREAD

**Issue by spike-bepop** [wubaiqing/zaobao#69]
> [类库] PostHTML 是一个用 JS 插件转换 HTML/XML 的工具，可以使用于表单生成器；支持，CLI、Webpack、Gulp 等：https://webkit.org/blog/8970/how-web-content-can-affect-power-usage/

**Comment by wubaiqing** [comment]
感谢指正。posthtml，链接：https://github.com/posthtml/posthtml
