### ISSUE TITLE
可以考虑用客户端的形式吗

### ISSUE THREAD

**Issue by nslogx** [wubaiqing/zaobao#7]
比如说微信小程序

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by wubaiqing** [comment]
提的意见很好，但我需要考虑一下。

我是站在这个角度上想的：
以目前分享的几大板块，如果看到感兴趣的内容，想要更深入的使用/理解，多数得用电脑实操。
因为整理分享内容，每天需要至少需要 1 个小时的时间，所以在项目初期还是以保障产出的质量为主。

我需要找到好的方式，把找内容的 “效率” 提升了以后，在去开发客户端。

谢谢你提供宝贵的意见！

**Comment by giscafer** [comment]
@wubaiqing @huangjianke 微信小程序已收录。后期会加入[sorrycc/zaobao](https://github.com/sorrycc/zaobao/issues) 和个人的一些早报。

![feweekly](https://user-images.githubusercontent.com/8676711/51784086-c79c0e80-217e-11e9-8fe7-86e624429801.jpg)

**Comment by wubaiqing** [comment]
@giscafer 👍棒！

是小程序有限制吗？链接无法正常跳转。

**Comment by giscafer** [comment]
@wubaiqing 是的，小程序限制非常大，所以提供了内容复制和原文链接复制，详细了解还需要复制或者电脑访问。
