### ISSUE TITLE
【通知】找到工作啦，6月15日开始，恢复更新；

### ISSUE THREAD

**Issue by wubaiqing** [wubaiqing/zaobao#73]
目前所在的公司是餐饮行业，也是受疫情影响最大的行业之一；
如果您的公司招聘 `中、高、专家` 级前端工程师、Java工程师、技术 Leader，请联系我。

现在研发团队 200 这些人面临着再找工作。
前端技术团队成员是我精心挑选过的（面试筛选的比例 1：80）。

目前在，北京-海淀-上地，附近工作。恳请大家帮忙内推。

**近期每日时报更新时间不太稳定，也请大家见谅。**

**Comment by xxholly32** [comment]
有什么要求吗？城市？工作内容？

**Comment by wubaiqing** [comment]
> 有什么要求吗？城市？工作内容？

工作地点在**北京**，目前预计 40 人：中、高级的 Java和前端需要找工作；

**Comment by jiangjiyun** [comment]
这个是字节内推官网，可以自行搜索岗位，投递简历： https://job.toutiao.com/s/oGpQaF

**Comment by wubaiqing** [comment]
> 这个是字节内推官网，可以自行搜索岗位，投递简历： https://job.toutiao.com/s/oGpQaF

好的，谢谢。

**Comment by wubaiqing** [comment]
工作已经找到啦，下周一开始，恢复更新。
