### ISSUE TITLE
催更不如自己更

### ISSUE THREAD

**Issue by xxholly32** [wubaiqing/zaobao#76]
😄😄😄

**Comment by xxholly32** [comment]
## 2020-6-7

[工具] 新一代可以运行在macOS, Windows, Linux, Android的新型浏览器brave [https://github.com/brave/brave-browser](https://github.com/brave/brave-browser)

[文章] chrome 83 原生表单的一些变化。[https://css-tricks.com/chrome-83-form-element-styles/](https://css-tricks.com/chrome-83-form-element-styles/)

## 2020-6-6

[文章] Chrome浏览器支持直接读写本地文件了 [https://juejin.im/post/5edb9e256fb9a047d245da72](https://juejin.im/post/5edb9e256fb9a047d245da72)

[工具]Mock Service Worker (MSW) 一个针对浏览和nodejs的 API 模拟库，它使用 Service Workers 拦截输出请求。[https://github.com/mswjs/msw](https://github.com/mswjs/msw)

[工具] 35+免费react模版库 [https://dev.to/davidepacilio/35-free-react-templates-and-themes-32ci](https://dev.to/davidepacilio/35-free-react-templates-and-themes-32ci)

## 2020-6-5

[文章] Unix命令行之美 简单几个实例介绍unix设计 强大之处 [https://prithu.xyz/posts/unix-pipeline/](https://prithu.xyz/posts/unix-pipeline/)

[文章] 软件吃软件，编程工作会越来越多吗？ [https://themargins.substack.com/p/software-will-eat-software-in-a-remote](https://themargins.substack.com/p/software-will-eat-software-in-a-remote)

[工具] 基于 微信小程序原生语法 实现的组件库 Lin UI [http://doc.mini.7yue.pro/](http://doc.mini.7yue.pro/)

## 2020-6-4

[文章] 尤雨溪：重头来过的 Vue 3 带来了什么？[https://mp.weixin.qq.com/s/eVsfQi9reILmThVxMsCNOA](https://mp.weixin.qq.com/s/eVsfQi9reILmThVxMsCNOA)

[文章] 玉伯：做一个简单自由有爱的技术人 [https://mp.weixin.qq.com/s/t7v5HcD8joqiv2p7ppA3zA](https://mp.weixin.qq.com/s/t7v5HcD8joqiv2p7ppA3zA)

**Comment by wubaiqing** [comment]
> ## 2020-6-7
> [工具] 新一代可以运行在macOS, Windows, Linux, Android的新型浏览器brave https://github.com/brave/brave-browser
> 
> [文章] chrome 83 原生表单的一些变化。https://css-tricks.com/chrome-83-form-element-styles/
> 
> ## 2020-6-6
> [文章] Chrome浏览器支持直接读写本地文件了 https://juejin.im/post/5edb9e256fb9a047d245da72
> 
> [工具]Mock Service Worker (MSW) 一个针对浏览和nodejs的 API 模拟库，它使用 Service Workers 拦截输出请求。https://github.com/mswjs/msw
> 
> [工具] 35+免费react模版库 https://dev.to/davidepacilio/35-free-react-templates-and-themes-32ci
> 
> ## 2020-6-5
> [文章] Unix命令行之美 简单几个实例介绍unix设计 强大之处 https://prithu.xyz/posts/unix-pipeline/
> 
> [文章] 软件吃软件，编程工作会越来越多吗？ https://themargins.substack.com/p/software-will-eat-software-in-a-remote
> 
> [工具] 基于 微信小程序原生语法 实现的组件库 Lin UI http://doc.mini.7yue.pro/
> 
> ## 2020-6-4
> [文章] 尤雨溪：重头来过的 Vue 3 带来了什么？https://mp.weixin.qq.com/s/eVsfQi9reILmThVxMsCNOA
> 
> [文章] 玉伯：做一个简单自由有爱的技术人 https://mp.weixin.qq.com/s/t7v5HcD8joqiv2p7ppA3zA

棒👍！

**Comment by wubaiqing** [comment]
工作已经找到啦，下周一开始，恢复更新。

**Comment by wubaiqing** [comment]
@xxholly32 感谢你的贡献；
