### ISSUE TITLE
新增计总数功能

### ISSUE THREAD

**Issue by xxholly32** [wubaiqing/zaobao#85]
一直觉得 今天是每日时报陪伴您的第 xxx 天这个用处不太大而且有点歧义，就是回头看“今天”不是当天的今天，而且主要每天加那句话太麻烦，so

我加了个自动计算的日期的插件，<https://github.com/xxholly32/zaobao-with-count-date/commit/b59fe3f3324637e87178df2d0096af5e838a803f> 

具体还得看您这边的设计 🚀

**Comment by wubaiqing** [comment]
陪伴第多少天，我是参考逻辑思维的[罗胖 60 秒](https://mp.weixin.qq.com/s?__biz=MjM5NjAxOTU4MA==&mid=3009244869&idx=2&sn=fe5f901ef1a9598250b3c5c64a8e7578&chksm=904662d6a731ebc05893a9b865fe061785a22e9d2658d63caecad383d44d3fe0e4bf95914b8b&xtrack=1&scene=90&subscene=93&sessionid=1593396351&clicktime=1593396360&enterid=1593396360&ascene=56&devicetype=android-29&version=27000f51&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&exportkey=AcDCB4GLaKdo7hRbpEUeG2A%3D&pass_ticket=HSBykgsm%2BROjuxj6eDnkE2Z5VQv7Jd8EMZz1M18hcRE%3D&wx_header=1)和[吴军的硅谷来信](https://m.igetget.com/share/course/pay/detail?id=1w2YlEkp7AMKr5ahY3Xy4Zd8oLjg0a)。它们有一些共同点是用编号，来记录这是多少期。

我发现这么做有一些好处：
1. **宣传**，做分享就是自己获得收获后同时也让他人受益。因为有利他的属性，所以避免不了**宣传**从而让更多的人知道这款产品。那么怎么获得别人的关注呢？就是你要证明它是靠谱（可持续维护的）的。所以坚持多少天，可以起到宣传的目的。
2. **被动学习**，如果做到一定规模后，有一定的用户群体，才会有被动学习的机会。以我这次找工作熟悉环境等停更行为举例，就是因为早起的宣传，才有了用户群体，当我停更时，大家能顶上来从而也让我有了**被动学习**的机会。
3. **监督**，做开源项目，最难的是坚持，因为这种坚持可能要长达几年；如果每天打上一个‘标号’，自己就能知道，做这件事总共坚持了多少天，从而也是为了让自己维护下去。阶梯式的成长，比汇总式的结果为更重要。

最后：每天手动加，我也觉得挺麻烦的。哈哈~~~

**Comment by xxholly32** [comment]
👌
