### ISSUE TITLE
推荐: 创建一个对象用 {} 还是用 Object.create(null)? 

### ISSUE THREAD

**Issue by ff131517** [wubaiqing/zaobao#9]
作者讲述了为什么一些框架内部使用  
```javascript
let obj = Object.create(null)
```
来创建对象,而不是使用字面量
```javascript
let obj  = {}
```
我认为值得一看

 链接 : [详解Object.create(null)](https://juejin.im/post/5acd8ced6fb9a028d444ee4e)

**Comment by wubaiqing** [comment]
👍感谢你多次的分享。会收录到29号日报中
